### ISSUE TITLE
Using Javascript's atob to decode base64 doesn't properly decode utf-8 strings

### ISSUE THREAD

**Issue by Comee** [lydian/jupyterlab_hubshare#3]
https://github.com/lydian/jupyterlab_hubshare/blob/cff1fe47dcc78efbd6a774f3ae84bdd9e4832934/src/index.ts#L115

should change
``` ts
atob(path)
```

to 
``` ts
decodeURIComponent(Array.prototype.map.call(atob(path), function(c) {
    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2)
}).join(''))
```

or using a base64 lib [js-base64](https://www.npmjs.com/package/js-base64)

**Comment by lydian** [comment]
Thanks for reporting and pull request! Would you mind fix the lint issue so that I can merge the change? Thanks!
